CREATE TYPE role_enum AS ENUM ('kontributor', 'verifikator', 'administrator');
CREATE TYPE status_enum AS ENUM ('pending', 'verified', 'rejected');

CREATE TABLE arkeolog (
  arkeolog_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_lengkap VARCHAR(255) NOT NULL,
  afiliasi_institusi VARCHAR(255) NOT NULL,
  spesialisasi VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  nomor_telepon VARCHAR(20) NOT NULL
);

CREATE TABLE kerajaan (
  kerajaan_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_kerajaan VARCHAR(255) NOT NULL,
  tahun_berdiri INT,
  tahun_runtuh INT,
  pusat_pemerintahan VARCHAR(255),
  deskripsi_singkat TEXT NOT NULL
);

CREATE TABLE kota_kabupaten (
    kota_kabupaten_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_kota_kabupaten VARCHAR(255) NOT NULL
);

CREATE TABLE tokoh (
  tokoh_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_tokoh VARCHAR(255) NOT NULL,
  tahun_lahir INT,
  tahun_wafat INT,
  biografi_singkat TEXT NOT NULL,
  kerajaan_id INT,
  FOREIGN KEY (kerajaan_id) REFERENCES kerajaan(kerajaan_id)
);

CREATE TABLE kecamatan (
    kecamatan_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_kecamatan VARCHAR(255) NOT NULL,
    kota_kabupaten_id INT NOT NULL,
    FOREIGN KEY (kota_kabupaten_id) REFERENCES kota_kabupaten(kota_kabupaten_id)
);

CREATE TABLE desa_kelurahan (
    desa_kelurahan_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_desa_kelurahan VARCHAR(255) NOT NULL,
    kecamatan_id INT NOT NULL,
    FOREIGN KEY (kecamatan_id) REFERENCES kecamatan(kecamatan_id)
);

CREATE TABLE pengguna (
  pengguna_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_pengguna VARCHAR(100) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  role role_enum NOT NULL DEFAULT 'kontributor'
);

CREATE TABLE situs_arkeologi (
  situs_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_situs VARCHAR(255) NOT NULL,
  jalan_dusun VARCHAR(255) NOT NULL,
  desa_kelurahan_id INT NOT NULL,
  latitude DECIMAL(9,6) NOT NULL,
  longitude DECIMAL(9,6) NOT NULL,
  periode_sejarah VARCHAR(255),
  jenis_situs VARCHAR(255) NOT NULL,
  kerajaan_id INT,
  FOREIGN KEY (kerajaan_id) REFERENCES kerajaan(kerajaan_id),
  FOREIGN KEY (desa_kelurahan_id) REFERENCES desa_kelurahan(desa_kelurahan_id)
);

CREATE TABLE objek_temuan (
  objek_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_objek VARCHAR(255) NOT NULL,
  jenis_objek VARCHAR(255) NOT NULL,
  bahan VARCHAR(255) NOT NULL,
  panjang DECIMAL(5,2) NOT NULL,
  tinggi DECIMAL(5,2) NOT NULL,
  lebar DECIMAL(5,2) NOT NULL,
  teks_transliterasi TEXT,
  aksara VARCHAR(255),
  bahasa VARCHAR(255),
  situs_id INT NOT NULL,
  FOREIGN KEY (situs_id) REFERENCES situs_arkeologi(situs_id)
);

ALTER TABLE situs_arkeologi
ADD COLUMN status_verifikasi status_enum NOT NULL DEFAULT 'pending',
ADD COLUMN pengguna_pelapor_id INT,
ADD FOREIGN KEY (pengguna_pelapor_id) REFERENCES pengguna(pengguna_id);

ALTER TABLE objek_temuan
ADD COLUMN status_verifikasi status_enum NOT NULL DEFAULT 'pending',
ADD COLUMN pengguna_pelapor_id INT,
ADD FOREIGN KEY (pengguna_pelapor_id) REFERENCES pengguna(pengguna_id);

CREATE TABLE penelitian_situs (
  arkeolog_id INT NOT NULL,
  situs_id INT NOT NULL,
  PRIMARY KEY (arkeolog_id, situs_id),
  FOREIGN KEY (arkeolog_id) REFERENCES arkeolog(arkeolog_id),
  FOREIGN KEY (situs_id) REFERENCES situs_arkeologi(situs_id)
);

CREATE TABLE atribusi_artefak (
  objek_id INT NOT NULL,
  tokoh_id INT NOT NULL,
  PRIMARY KEY (objek_id, tokoh_id),
  FOREIGN KEY (objek_id) REFERENCES objek_temuan(objek_id),
  FOREIGN KEY (tokoh_id) REFERENCES tokoh(tokoh_id)
);

CREATE TABLE tokoh_gelar_tokoh (
  gelar_tokoh VARCHAR(255) NOT NULL,
  tokoh_id INT NOT NULL,
  PRIMARY KEY (gelar_tokoh, tokoh_id),
  FOREIGN KEY (tokoh_id) REFERENCES tokoh(tokoh_id)
);